import { colors, fonts, sizes } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: {
    flex: 1,
    paddingTop: 16,
    paddingHorizontal: 8,
  },
  headerTitle: {
    fontFamily: fonts.bold,
    fontSize: 20,
    color: colors.white,
    marginBottom: 24,
    marginTop: 8,
  },
  mainCard: {
    backgroundColor: colors["blue--700"],
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    position: 'relative',
    overflow: 'hidden',
  },
  mainCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    zIndex: 1,
  },
  badgeHatch: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
  },
  badgeHatchText: {
    color: colors["green--500"],
    fontFamily: fonts.medium,
    fontSize: 14,
  },
  badgeAtivo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 16,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors["green--500"],
    marginRight: 6,
  },
  badgeAtivoText: {
    color: colors["green--500"],
    fontFamily: fonts.bold,
    fontSize: 12,
    textTransform: 'uppercase',
  },
  carImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 120,
    marginBottom: 16,
  },
  carImage: {
    opacity: 0.2, // Ghost effect
  },
  mainCardBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    zIndex: 1,
  },
  carName: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  carDetails: {
    color: colors["blue--300"],
    fontFamily: fonts.regular,
    fontSize: 14,
    marginTop: 4,
  },
  carPlate: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  infoCardsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  infoCard: {
    backgroundColor: colors["blue--700"],
    borderRadius: 12,
    padding: 16,
    width: '48%',
  },
  infoCardLabel: {
    color: colors["blue--300"],
    fontFamily: fonts.medium,
    fontSize: 10,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  infoCardValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  infoCardValue: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  infoCardUnit: {
    color: colors["green--500"],
    fontFamily: fonts.medium,
    fontSize: 14,
    marginLeft: 4,
  },
  infoIcon: {
    position: 'absolute',
    bottom: 8,
    right: 8,
  },
  sectionTitle: {
    color: colors["blue--300"],
    fontFamily: fonts.medium,
    fontSize: 14,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  identificationCard: {
    backgroundColor: colors["blue--700"],
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
  },
  identItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  identIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  identTextContainer: {
    flex: 1,
  },
  identLabel: {
    color: colors["blue--300"],
    fontFamily: fonts.regular,
    fontSize: 12,
  },
  identValue: {
    color: colors.white,
    fontFamily: fonts.medium,
    fontSize: 14,
    marginTop: 2,
  },

  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors["blue--900"],
  },
  loadingText: {
    color: colors.white,
    marginTop: 12,
    fontFamily: fonts.medium,
  },
  tooltipContainer: {
    backgroundColor: colors["blue--900"],
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors["blue--600"],
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    marginBottom: 16,
  },
  tooltipText: {
    fontFamily: fonts.medium,
    fontSize: 14,
    color: colors.white,
    lineHeight: 20,
  },
});
